name: ci-cd-nextjs-gcp 
on: 
  push: 
    branches:
      - main 
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} 
  GCP_REGION: us-centrall 
  REPOSITORY: ci-cd-nextjs-gcp
jobs: 
  install-build-test-deploy:
    name: Install, build, test and deploy nextjs application 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout
      uses: actions/checkout@v2 
    - uses: google-github-actions/setup-gcloud@v0.2.0 
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }} 
        service_account_key: ${{ secrets.GCP SA KEYBASE64 }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }} 
    - name: Enable all the apis required in GCP, 
      run: |-
        gcloud services enable containerregistry.googleapis.com 
        gcloud services enable run.googleapis.com
        gcloud --quiet auth configure-docker 
    - name: Build image 
      run: |-
        docker build . --tag "ger.io/$GCP_PROJECT_ID/$REPOSITORY: $GITHUB_SHA" 
    - name: Push image to GCP container registry 
      run: |-
        docker push gcr.io/$GCP_PROJECT_ID/$REPOSITORY: $GITHUB_SHA 
    - name: Deploy image 
      run: |-
        gcloud components install beta --quiet
        gcloud beta run deploy $REPOSITORY --image ger.io/$GCP_PROJECT_ID/$REPOSITORY:$GITHUB_SHA \
          --project $GCP_PROJECT_ID 
          --platform managed 
          --region $GCP_REGION 
          --min-instances=1 
          --max-instances=1 
          --allow-unauthenticated 
          --quiet
